### ISSUE TITLE
MER v2.3 refresher (one-pager)

### ISSUE THREAD

**Issue by petersonml** [ICPI/Diagnosis-Cluster#3]

**Comment by cnichols3h** [comment]
This product is finished and can be found at: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FClusters%2FHIV-TB%20Diagnosis%2FResources&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D
